// Import the JetBrains Mono font from Google Fonts using Next.js font optimization
import { JetBrains_Mono } from "next/font/google";
// Import global CSS styles
import "./globals.css";

// Import reusable components
import Header from "@/components/Header"; // Header component for navigation
import PageTransition from "@/components/PageTransition"; // Component for smooth page transitions
import StairTransition from "@/components/StairTransition"; // Component for staircase-like animations

// Configure the JetBrains Mono font
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"], // Specify the character set for the font
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // Include multiple font weights for flexibility
  variable: "--font-jetbrainsMono", // CSS variable to use the font throughout the app
});

// Define metadata for the application
export const metadata = {
  title: "My Portfolio", // Title of the website
  description: "Generated by create next app", // Description of the website
};

// Define the root layout component
export default function RootLayout({ children }) {
  return (
    // Set the HTML language to English
    <html lang="en">
      <body
        // Apply the JetBrains Mono font and enable antialiasing for smoother text
        className={`${jetbrainsMono.variable} antialiased`}
      >
        {/* Include the Header component for the navigation bar */}
        <Header />
        {/* Add the StairTransition component for staircase animations */}
        <StairTransition />
        {/* Wrap children components with the PageTransition for smooth transitions */}
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
